baseurl = "https://oakeslabmtl.github.io/dtdf-dtscribe/"
title = "Digital Twin Reporting Summary"
author = "KÃ©rian Fiter"
canonifyurls = true
languagecode = "en"
theme = "my-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Digital Twin Reporting Summary"
  disableWebFonts = true